version: '3.8'

services:

  db:
    

    image: postgres:16.4
    restart: always
    ports:
     - "5555:5432" 
    shm_size: 128mb
    environment:
       POSTGRES_USER: user1
       POSTGRES_PASSWORD: password1
       POSTGRES_DB: my_database
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    
<<<<<<< HEAD
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8080:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin  

volumes:
  postgres-data:
 
=======



volumes:
  postgres-data:
>>>>>>> c43237d (Revert "Remove unused lines")
