# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    build:

      context: .
      dockerfile: DockerFile

    image: postgres:16.4
    restart: always
    ports:
     - "5432:5432" 
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
       POSTGRES_USER: user1
       POSTGRES_PASSWORD: password1
       POSTGRES_DB: my_database
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5555:5555
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin   
  

volumes:
  postgres-data:
