version: '3.8'

services:

  db:
    

    image: postgres:16.4
    restart: always
    ports:
     - "5123:5123" 
    shm_size: 128mb
  
    environment:
       POSTGRES_USER: user1
       POSTGRES_PASSWORD: password1
       POSTGRES_DB: my_database
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    



volumes:
  postgres-data:
