
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: weather_analysis
version: '1.0.0'
config-version: 2

profile: weather_analysis

vars:
    "dbt_date:time_zone": "Europe/Paris"
#sources:
 # _dbt_weather:
  #  +enabled: true
models:
  weather_analysis:
    marts:
      dimensions:
        +materialized: table
      facts:
        +materialized: table  
      intermediate: 
        +materialized: view
    