weather_analysis:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: DATA_ANALYTICS
      role: dbt_transform
      schema: transformations
      threads: 8
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      warehouse: dbt_weather
  target: dev
