version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  python-app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: python-postgres-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user1:password1@db/my_database
    tty: true
      
volumes:
  pgdata:
