version: 2

models:
  - name: fact_weather
    description: "A fact table that contains weather measurements, associated with city and country dimensions, by date."
    columns: 
      - name: fact_weather_key
        description: "Unique key for each record in the fact_weather table, generated as a surrogate key."
        tests:
          - not_null
          - unique

      - name: city_id
        description: "Unique identifier for the city associated with the weather data, linking to dim_cities_countries."
        tests:
          - not_null
          - relationships:
              to: ref('dim_cities_countries')
              field: city_id

      - name: country_id
        description: "Unique identifier for the country associated with the weather data, linking to dim_cities_countries."
        tests:
          - relationships:
              to: ref('dim_cities_countries')
              field: country_id

      - name: date_key
        description: "Date identifier, linking to dim_date for the specific date of the weather data."
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
