name: dbt_modeling
version: 1.0.0
config-version: 2

profile: dbt_modeling

models:
  dbt_modeling: 
    marts: 
      appointment:
        +materialized: table
      dimensions: 
        +materialized: table
    
